<?php
/**
 * Copyright (c) 2020. Alsurmedia
 * Author: Santiago Bermejo - sbermejo@alsurmedia.com
 * Site: https://alsurmedia.com
 */

?>

<style>
    .copyright.col-m-6 span.copyright {
        font-size: 100%;
        margin-bottom: 10px;
        position: relative;
    }
    .copyright.col-m-6 span.copyright span {
        padding-left: 35px;
        font-size: 100%;
    }
    .copyright.col-m-6 span {
        display: block;
        font-size: 12px;
    }
    .copyright.col-m-6 span a {
        color: #a81e94;
    }
    .copyright.col-m-6 .skype {
        padding-top: 5px;
    }

    span.copyright img {
        float: left;
        width: 40px;
        margin: 0 10px 0 0;
    }
</style>
<span class="copyright">
    <img src="<?php echo $this->getViewFileUrl('Alsurmedia_Faq::images/alsur_logo.png') ?>"/>
    <span><a href="https://alsurmedia.com" target="_blank">Alsurmedia.com</a> <br>Copyright © 2020. All rights reserved.</span>
</span>
