<?php if ($this->getFaqCategoriesList()): ?>
    <div class="block block-faq-category faq__category--sidebar">
        <div class="faq__category--sidebar-title block-title">
            <strong><?php echo __('Categories'); ?></strong>
        </div>
        <div class="faq__category--sidebar-content block-content">
            <ol class="items">
                <?php foreach($this->getFaqCategoriesList() as $fclist): ?>
                    <li class="faq__category--sidebar-content-item item">
                        <a href="<?php echo $this->getFaqcategoryFullPath($fclist['identifier']); ?>">
                            <?php echo __($fclist['title']); ?> <span class="count">(<?php echo $fclist['count']; ?>)</span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
